import React from "react";
import { Printer } from "lucide-react";
import { ageGroups, contextTips } from "./AnimalTeachers";

const PrintableLesson = ({ translation, ageGroup, context }) => {
  if (!translation || translation.error) return null;

  const ageInfo = ageGroups[ageGroup] || { label: ageGroup, range: "" };
  const ctxInfo = contextTips[context] || { label: context };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div>
      {/* Print button - hidden during print */}
      <button
        onClick={handlePrint}
        className="no-print flex items-center gap-2 px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-all text-sm font-medium mx-auto"
        aria-label="Print this lesson"
      >
        <Printer className="w-4 h-4" />
        Print Lesson
      </button>

      {/* Printable content - always in DOM, styled for print via CSS */}
      <div className="print-only" role="document" aria-label="Printable lesson plan">
        <div style={{ fontFamily: "Georgia, serif", maxWidth: "700px", margin: "0 auto", padding: "20px" }}>
          <h1 style={{ textAlign: "center", fontSize: "24pt", marginBottom: "4px" }}>
            {translation.teacher.emoji} {translation.teacher.name}
          </h1>
          <p style={{ textAlign: "center", fontSize: "12pt", color: "#666", marginBottom: "20px" }}>
            Bio-Cognitive Lesson Plan - {ageInfo.label} (Ages {ageInfo.range}) - {ctxInfo.label}
          </p>

          <hr style={{ margin: "16px 0" }} />

          <h2 style={{ fontSize: "16pt" }}>
            Concept: {translation.original_concept.charAt(0).toUpperCase() + translation.original_concept.slice(1).replace(/_/g, " ")}
          </h2>
          <p style={{ fontSize: "10pt", color: "#888" }}>
            Category: {translation.category} | Key terms: {translation.explanation.keywords}
          </p>

          <h3 style={{ fontSize: "14pt", marginTop: "20px" }}>The Story</h3>
          <p style={{ fontSize: "12pt", lineHeight: "1.6" }}>{translation.explanation.story}</p>

          <h3 style={{ fontSize: "14pt", marginTop: "20px" }}>Hands-On Activity</h3>
          <p style={{ fontSize: "12pt", lineHeight: "1.6" }}>{translation.activity.main_activity}</p>

          <h4 style={{ fontSize: "12pt", marginTop: "12px" }}>Materials Needed:</h4>
          <ul style={{ fontSize: "11pt" }}>
            {translation.activity.materials_needed.map((m, i) => (
              <li key={i} style={{ marginBottom: "4px" }}>{m}</li>
            ))}
          </ul>

          {translation.contextTip && (
            <>
              <h4 style={{ fontSize: "12pt", marginTop: "12px" }}>Teaching Tip:</h4>
              <p style={{ fontSize: "11pt", fontStyle: "italic" }}>{translation.contextTip}</p>
            </>
          )}

          <h3 style={{ fontSize: "14pt", marginTop: "20px" }}>Mind-Blowing Fact</h3>
          <p style={{ fontSize: "12pt", lineHeight: "1.6" }}>{translation.wow_fact}</p>

          <hr style={{ margin: "24px 0" }} />
          <p style={{ fontSize: "9pt", color: "#aaa", textAlign: "center" }}>
            Generated by Bio-Cognitive Concept Translator - The Curriculum of Everything Earth
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrintableLesson;
